version: "3.9"
x-logging: &default-logging
  driver: json-file
  options:
    tag: "{{.Name}}"
x-env-file:
  env_file: &default-env-file .env
services:
  db:
    container_name: db
    image: ${REGISTRY_PREFIX}postgres:14.1
    command: -p ${POSTGRES_PORT}
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    env_file: *default-env-file
    logging: *default-logging
  api:
    container_name: api
    build: api
    image: ${REGISTRY_PREFIX}xpqf_greeter_api:${TAG}
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - db
    env_file: *default-env-file
    logging: *default-logging
  app:
    container_name: app
    build: app
    image: ${REGISTRY_PREFIX}xpqf_greeter_app:${TAG}
    ports:
      - "${APP_PORT}:80"
    depends_on:
      - api
    env_file: *default-env-file
    logging: *default-logging
