version: "3.9"
x-logging: &default-logging
  driver: json-file
  options:
    tag: "{{.Name}}"
services:
  db:
    container_name: db
    image: postgres
    env_file: .env.local
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    logging: *default-logging
    ports:
      - "5432:5432"
  api:
    container_name: api
    build: api
    image: xpqf_greeter_api
    env_file: .env.local
    logging: *default-logging
    ports:
      - "8081:8081"
  app:
    container_name: app
    build: app
    image: xpqf_greeter_app
    logging: *default-logging
    ports:
      - "8080:80"
