version: "3.9"
x-logging: &default-logging
  driver: json-file
  options:
    tag: "{{.Name}}"
services:
  api:
    container_name: api
    build: api
    logging: *default-logging
    ports:
      - "8080:8080"
  app:
    container_name: app
    build: app
    logging: *default-logging
    ports:
      - "8081:8081"
