version: "3.9"
x-logging: &default-logging
  driver: json-file
  options:
    tag: "{{.Name}}"
x-env-file:
  env_file: &default-env-file swarm/temp/.env.${STACK}
networks:
  internal:
    driver: overlay # Note: same as default network, defined explicitly for readability
  traefik-public: # Use the previously created public network "traefik-public"
    external: true
services:
  db:
    container_name: db
    image: postgres
    command: -p ${POSTGRES_PORT}
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - internal
    env_file: *default-env-file
    logging: *default-logging

  api:
    container_name: api
    build: api
    image: xpqf_greeter_api
    networks:
      - internal
      - traefik-public
    env_file: *default-env-file
    logging: *default-logging
    deploy:
      labels:
        - traefik.enable=true
        - traefik.constraint-label=traefik-public
        - traefik.docker.network=traefik-public
        - traefik.http.services.${STACK}_api.loadbalancer.server.port=${API_PORT}
        - "traefik.http.routers.${STACK}_api.rule=Host(`api.${STACK}.localhost`)"
  app:
    container_name: app
    build: app
    image: xpqf_greeter_app
    networks:
      - traefik-public
    env_file: *default-env-file
    logging: *default-logging
    deploy:
      labels:
        - traefik.enable=true
        - traefik.constraint-label=traefik-public
        - traefik.http.services.${STACK}_app.loadbalancer.server.port=80
        - "traefik.http.routers.${STACK}_app.rule=Host(`app.${STACK}.localhost`)"
