version: "3.9"
networks:
  traefik-network:
    external: true
services:
  registry:
    image: registry:2.7
    networks:
      - traefik-network
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.constraint-label=traefik-public"

        # Route HTTPS to service
        - "traefik.http.routers.registry.entrypoints=https"
        - "traefik.http.routers.registry.rule=Host(`registry.${SWARM_HOST}`)"
        - "traefik.http.routers.registry.tls=true"
        - "traefik.http.routers.registry.service=registry"
        - "traefik.http.services.registry.loadbalancer.server.port=5000"
