version: "3.9"
services:
  traefik:
    image: traefik:v2.5
    command:
      # Enable Docker in Traefik, so that it reads labels from Docker services
      - --providers.docker

      # Add a constraint to only use services with the label "traefik.constraint-label=traefik-public"
      - --providers.docker.constraints=Label(`traefik.constraint-label`, `traefik-public`)

      # Do not expose all Docker services, only the ones explicitly exposed
      - --providers.docker.exposedbydefault=false

      # Enable Docker Swarm mode
      - --providers.docker.swarmmode

      # Point to dynamic config file
      - --providers.file.filename=/etc/traefik/dynamic.yml

      # Create an entrypoint "http" listening on port 80
      - --entrypoints.http.address=:80

      # Create an entrypoint "https" listening on port 443
      - --entrypoints.https.address=:443

      # Enable the access log, with HTTP requests
      # - --accesslog

      # Enable the Traefik log, for configurations and errors
      - --log
      # - --log.level=DEBUG

      # Enable the Dashboard and API
      - --api
      - --api.insecure=true

    networks:
      - traefik-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./swarm/local/cert:/etc/cert
      - ./swarm/traefik/dynamic.yml:/etc/traefik/dynamic.yml
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.constraint-label=traefik-public"

        - "traefik.http.services.traefik.loadbalancer.server.port=8080"

        - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
        - "traefik.http.middlewares.https-redirect.redirectscheme.permanent=true"

        - "traefik.http.routers.traefik-public-http.entrypoints=http"
        - "traefik.http.routers.traefik-public-http.rule=Host(`traefik.${SWARM_HOST}`)"
        - "traefik.http.routers.traefik-public-http.middlewares=https-redirect"

        - "traefik.http.routers.traefik-public-https.entrypoints=https"
        - "traefik.http.routers.traefik-public-https.rule=Host(`traefik.${SWARM_HOST}`)"
        - "traefik.http.routers.traefik-public-https.tls=true"
        - "traefik.http.routers.api.service=api@internal"

networks:
  traefik-network:
    external: true
