# Note: environment specific sections for registry/docker-compose.yml

# Note: Use Let's Encrypt certificate resolver defined below
x-tls-label: &tls-label "traefik.http.routers.registry.tls.certresolver=le"
